version: '3.2'
services:
  zookeeper:
    image: zookeeper:3.6.2
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      ZOO_PORT: 2181

  kafka1:
    image: wurstmeister/kafka:2.12-2.4.1
    hostname: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: ${IP}
      KAFKA_ADVERTISED_PORT: 9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP}:9091
      KAFKA_LISTENERS: PLAINTEXT://:9091
      KAFKA_HEAP_OPTS: -Xmx1G -Xms1G
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
  kafka2:
    image: wurstmeister/kafka:2.12-2.4.1
    hostname: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: ${IP}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP}:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_HEAP_OPTS: -Xmx1G -Xms1G
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
  kafka3:
    image: wurstmeister/kafka:2.12-2.4.1
    hostname: kafka3
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: ${IP}
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP}:9093
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_HEAP_OPTS: -Xmx1G -Xms1G
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  kafka-manager:
    image: kafkamanager/kafka-manager:3.0.0.4
    restart: always
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_BROKERS: kafka1:9090


  kafdrop:
    image: obsidiandynamics/kafdrop:3.28.0-SNAPSHOT
    ports:
      - "9001:9001"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:9091"
      SERVER_PORT: 9001
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
